export const firstVariants = [
  {
    id: "First 6 Inch Sub_Chatpata Chana",
    title: "Chatpata Chana",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "First 6 Inch Sub_Hara Bhara Kebab",
    title: "Hara Bhara Kebab",
    stock: false,
    checked: false,
    type: "single",
  },
  {
    id: "First 6 Inch Sub_Mexican Patty",
    title: "Mexican Patty",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "First 6 Inch Sub_Veg Seekh",
    title: "Veg Seekh",
    stock: true,
    checked: false,
    type: "single",
  },
];
export const secondVariants = [
  {
    id: "Second 6 Inch Sub_Chatpata Chana",
    title: "Chatpata Chana",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Second 6 Inch Sub_Hara Bhara Kebab",
    title: "Hara Bhara Kebab",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Second 6 Inch Sub_Mexican Patty",
    title: "Mexican Patty",
    stock: false,
    checked: false,
    type: "single",
  },
  {
    id: "Second 6 Inch Sub_Veg Seekh",
    title: "Veg Seekh",
    stock: true,
    checked: false,
    type: "single",
  },
];
export const breadVariants = [
  {
    id: "Bread_Multigrain",
    title: "Multigrain",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Bread_Multigrain Honey Oats",
    title: "Multigrain Honey Oats",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Bread_White Italian",
    title: "White Italian",
    stock: false,
    checked: false,
    type: "single",
  },
  {
    id: "Bread_Roasted Garlic",
    title: "Roasted Garlic",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Bread_Parmesan Oregano",
    title: "Parmesan Oregano",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Bread_Flat",
    title: "Flat",
    stock: true,
    checked: false,
    type: "single",
  },
];
export const preparationVariants = [
  {
    id: "Preparation_Plain Bread",
    title: "Plain Bread",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Preparation_Plain Bread With Cheese Slice",
    title: "Plain Bread With Cheese Slice",
    stock: false,
    checked: false,
    type: "single",
  },
  {
    id: "Preparation_Toasted Bread",
    title: "Toasted Bread",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Preparation_Toasted Bread With Cheese Slice",
    title: "Toasted Bread With Cheese Slice",
    stock: true,
    checked: false,
    type: "single",
  },
  {
    id: "Preparation_Toasted With Mozzarella Cheese",
    title: "Toasted With Mozzarella Cheese",
    stock: true,
    checked: false,
    type: "single",
  },
];
export const sauceVariants = [
  {
    id: "Sauce Any (3)_Mayonnaise",
    title: "Mayonnaise",
    stock: true,
    checked: false,
    type: "multiple",
    limit: "3",
  },
  {
    id: "Sauce Any (3)_Mint Mayonnaise",
    title: "Mint Mayonnaise",
    stock: false,
    checked: false,
    type: "multiple",
    limit: "3",
  },
  {
    id: "Sauce Any (3)_Chipotle South West",
    title: "Chipotle South West",
    stock: true,
    checked: false,
    type: "multiple",
    limit: "3",
  },
  {
    id: "Sauce Any (3)_Honey Mustard",
    title: "Honey Mustard",
    stock: true,
    checked: false,
    type: "multiple",
    limit: "3",
  },
  {
    id: "Sauce Any (3)_Red Chilli",
    title: "Red Chilli",
    stock: true,
    checked: false,
    type: "multiple",
    limit: "3",
  },
  {
    id: "Sauce Any (3)_Marinara",
    title: "Marinara",
    stock: true,
    checked: false,
    type: "multiple",
    limit: "3",
  },
  {
    id: "Sauce Any (3)_Barbeque",
    title: "Barbeque",
    stock: false,
    checked: false,
    type: "multiple",
    limit: "3",
  },
  {
    id: "Sauce Any (3)_Tandoori Mayo",
    title: "Tandoori Mayo",
    stock: false,
    checked: false,
  },
  {
    id: "Sauce Any (3)_Sweet Onion",
    title: "Sweet Onion",
    stock: true,
    checked: false,
    type: "multiple",
    limit: "3",
  },
];

export const vegetableVariants = [
  {
    id: "Vegetables_Lettuce",
    title: "Lettuce",
    stock: true,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Tomato",
    title: "Tomato",
    stock: true,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Cucumber",
    title: "Cucumber",
    stock: true,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Pickle",
    title: "Pickle",
    stock: true,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Capsicum",
    title: "Capsicum",
    stock: true,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Olives",
    title: "Olives",
    stock: true,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Onions",
    title: "Onions",
    stock: false,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Jalapenos",
    title: "Jalapenos",
    stock: true,
    checked: false,
    type: "multiple",
  },
  {
    id: "Vegetables_Salt and Pepper",
    title: "Salt and Pepper",
    stock: true,
    checked: false,
    type: "multiple",
  },
];
